apiVersion: v1
kind: Secret
metadata:
  name: crud-mongodb-secrets
  namespace: mongodb # 사용하는 네임스페이스로 변경 가능
type: Opaque
stringData:
  # 1. 🌟 CRUD 프로젝트에서 실제로 사용할 핵심 데이터 관리자 계정
  MONGODB_DATABASE_ADMIN_USER: "root"
  MONGODB_DATABASE_ADMIN_PASSWORD: "Password123!"

  # 2. 클러스터 노드 간 통신 및 관리를 위한 계정 (오퍼레이터 필수)
  MONGODB_CLUSTER_ADMIN_USER: "clusterAdmin"
  MONGODB_CLUSTER_ADMIN_PASSWORD: "Password123!"

  # 3. DB 사용자 계정 추가/삭제 관리를 위한 계정
  MONGODB_USER_ADMIN_USER: "userAdmin"
  MONGODB_USER_ADMIN_PASSWORD: "Password123!"

  # 4. 백업 및 모니터링을 위한 계정
  MONGODB_BACKUP_USER: "backup"
  MONGODB_BACKUP_PASSWORD: "Password123!"
