postgres-config {
  n-threads = 32
  url = "jdbc:postgresql://crud-postgres-rw.postgres:5432/notes_db"
  user = "admin"
  pass = "5q5SP5RIoaq7ZlmBxmtJ4lPjqoXhvcufCJBOngOEEB3PaZckSQ4RZ3vgeU2A2hXP"
}

ember-config {
  host = "0.0.0.0"
  port = 5002
}

redis-config {
  host = "redis"
  port = 26379
  pass = "Password123!"
  master-set = "mymaster"
}

