postgres-config {
  n-threads = 32
  url = "jdbc:postgresql://crud-postgres-rw.postgres:5432/notes_db"
  user = "admin"
  user = ${?DB_USER}
  pass = ${DB_PASS}
}

ember-config {
  host = "0.0.0.0"
  port = 5002
}

redis-config {
  host = "redis"
  port = 26379
  pass = ${REDIS_PASS}
  master-set = "mymaster"
}

