server:
  port: 5003

spring:
  application:
    name: custom-kotlin-api

  datasource:
    # 💡 쿠버네티스 포트포워딩(kubectl port-forward) 사용 시: jdbc:postgresql://localhost:5432/notes_db_kotlin
    # 💡 쿠버네티스 클러스터 내부 배포 시: jdbc:postgresql://<service-name>.<namespace>.svc.cluster.local:5432/notes_db_kotlin
    url: ${DB_URL:jdbc:postgresql://postgres-rw.postgres.svc.cluster.local:5432/notes_db_kotlin}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
#    hibernate:
#      ddl-auto: update # 테이블 자동 생성 (개발용)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
